# -*- coding: utf-8 -*-
"""Helmet Detection Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJaoTGo5MCiKLfKC6VJIfRFQ1inmiuNJ

## **Helmet Safety Detection**
"""

!gdown --id 1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R

!mkdir safety_helmet_dataset

!unzip -q '/content/Safety_Helmet_Dataset.zip' -d '/content/safety_helmet_dataset'

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10

!pip install -q -r requirements.txt

!pip install -e .

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

from ultralytics import YOLOv10

MODEL_PATH = 'yolov10n.pt'

model = YOLOv10(MODEL_PATH)

YAML_PATH = '../safety_helmet_dataset/data.yaml'

EPOCHS = 50

IMG_SIZE = 320

BATCH_SIZE = 64

import torch

torch.cuda.empty_cache()

model.train(data=YAML_PATH,
            epochs=EPOCHS,
            batch=BATCH_SIZE,
            imgsz=IMG_SIZE,
            amp = True)

TRAINED_MODEL_PATH = 'runs/detect/train/weights/best.pt'

model = YOLOv10(TRAINED_MODEL_PATH)

model.val(data=YAML_PATH, imgsz=IMG_SIZE, split = 'test')

from google.colab.patches import cv2_imshow

TRAINED_MODEL_PATH = 'runs/detect/train/weights/best.pt'

model = YOLOv10(TRAINED_MODEL_PATH)

IMAGE_URL = '/content/safety_helmet_dataset/test/images/helmet-10-_jpg.rf.eee985865a1a52407316f0c9ea7a9b3e.jpg'

CONF_THRESHOLD = 0.3

results = model.predict(source=IMAGE_URL,
                        imgsz = IMG_SIZE,
                        conf=CONF_THRESHOLD)

annotated_img = results[0].plot()

cv2_imshow(annotated_img)